-- MySQL Script generated by MySQL Workbench
-- Sun Sep  1 23:22:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_matricula
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_matricula` ;

-- -----------------------------------------------------
-- Schema sistema_matricula
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_matricula` DEFAULT CHARACTER SET utf8 ;
USE `sistema_matricula` ;

-- -----------------------------------------------------
-- Table `sistema_matricula`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`curso` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creditos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `creditos` INT NOT NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disciplina_curso1_idx` (`curso_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_matricula`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`aluno` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`aluno` (
  `id_usuario` INT NOT NULL,
  `matricula` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_aluno_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_matricula`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`professor` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`professor` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_professor_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_matricula`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`status_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`status_turma` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`status_turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`semestre` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`semestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  `periodo` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`curriculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`curriculo` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`curriculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `semestre_id` INT NOT NULL,
  PRIMARY KEY (`id`, `semestre_id`),
  INDEX `fk_curriculo_semestre1_idx` (`semestre_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_curriculo_semestre1`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `sistema_matricula`.`semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`turma` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `min_alunos` INT NOT NULL DEFAULT 3,
  `max_alunos` INT NOT NULL DEFAULT 60,
  `id_professor` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `id_status_turma` INT NOT NULL DEFAULT 1,
  `id_curriculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_professor1_idx` (`id_professor` ASC) VISIBLE,
  INDEX `fk_turma_disciplina1_idx` (`id_disciplina` ASC) VISIBLE,
  INDEX `fk_turma_status_turma1_idx` (`id_status_turma` ASC) VISIBLE,
  INDEX `fk_turma_curriculo1_idx` (`id_curriculo` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `sistema_matricula`.`professor` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `sistema_matricula`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_status_turma1`
    FOREIGN KEY (`id_status_turma`)
    REFERENCES `sistema_matricula`.`status_turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_curriculo1`
    FOREIGN KEY (`id_curriculo`)
    REFERENCES `sistema_matricula`.`curriculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matricula`.`matricula_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_matricula`.`matricula_aluno` ;

CREATE TABLE IF NOT EXISTS `sistema_matricula`.`matricula_aluno` (
  `id_aluno` INT NOT NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aluno`, `id_turma`),
  INDEX `fk_aluno_has_turma_turma1_idx` (`id_turma` ASC) VISIBLE,
  INDEX `fk_aluno_has_turma_aluno1_idx` (`id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_turma_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `sistema_matricula`.`aluno` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_turma_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `sistema_matricula`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sistema_matricula`.`status_turma`
-- -----------------------------------------------------
START TRANSACTION;
USE `sistema_matricula`;
INSERT INTO `sistema_matricula`.`status_turma` (`id`, `nome`, `descricao`) VALUES (DEFAULT, 'MATRICULA_ABERTA', NULL);
INSERT INTO `sistema_matricula`.`status_turma` (`id`, `nome`, `descricao`) VALUES (DEFAULT, 'MATRICULA_FECHADA', NULL);
INSERT INTO `sistema_matricula`.`status_turma` (`id`, `nome`, `descricao`) VALUES (DEFAULT, 'INICIADA', NULL);
INSERT INTO `sistema_matricula`.`status_turma` (`id`, `nome`, `descricao`) VALUES (DEFAULT, 'TERMINADA', NULL);
INSERT INTO `sistema_matricula`.`status_turma` (`id`, `nome`, `descricao`) VALUES (DEFAULT, 'CANCELADA', NULL);
INSERT INTO `sistema_matricula`.`status_turma` (`id`, `nome`, `descricao`) VALUES (DEFAULT, 'CRIADA', NULL);

COMMIT;

